name: hack19
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: guilhermecastro <guilherme.torres.castro@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'



dependencies:
  webfeed: ^0.4.2
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
